site_name: Glazzbocks
repo_url: https://github.com/yourusername/glazzbocks
docs_dir: docs
nav:
  - Home: index.md
  - User Guide:
      - DataExplorer: dataexplorer.md
      - ModelInterpreter: modelinterpreter.md
      - ML Pipeline: ml_pipeline.md
  - API Reference: api.md
theme:
  name: material